import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

export interface ComplianceData {
  memberName: string;
  workspaceName: string;
  generated: string;
  ethicsAvg: number | null;
  flags: number;
  scoredCalls: number;
  recent: { at: string; title: string; overall: number; ethics: number | null; flagged: boolean }[];
}

const s = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#18181b' },
  h1: { fontSize: 18, fontFamily: 'Helvetica-Bold' },
  sub: { fontSize: 9, color: '#71717a', marginTop: 2, marginBottom: 16 },
  band: { flexDirection: 'row', gap: 24, marginBottom: 18, padding: 12, backgroundColor: '#f4f4f5', borderRadius: 6 },
  stat: { marginRight: 24 },
  statVal: { fontSize: 16, fontFamily: 'Helvetica-Bold' },
  statLabel: { fontSize: 8, color: '#71717a' },
  th: { flexDirection: 'row', borderBottom: '1 solid #d4d4d8', paddingBottom: 4, marginBottom: 4 },
  tr: { flexDirection: 'row', paddingVertical: 3, borderBottom: '0.5 solid #e4e4e7' },
  cDate: { width: '18%' }, cTitle: { width: '42%' }, cNum: { width: '13%', textAlign: 'right' },
  cFlag: { width: '14%', textAlign: 'right' },
  bold: { fontFamily: 'Helvetica-Bold' },
  warn: { color: '#dc2626', fontFamily: 'Helvetica-Bold' },
  okTxt: { color: '#16a34a' },
  foot: { position: 'absolute', bottom: 24, left: 40, right: 40, fontSize: 8, color: '#a1a1aa', borderTop: '1 solid #e4e4e7', paddingTop: 6 },
});

/** IRDAI-framed conduct report: ethics scores + mis-selling flags per scored
 *  call, generated from the same rubric that grades every practice session. */
export function CompliancePDF({ data }: { data: ComplianceData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Sales Conduct & Compliance Report</Text>
        <Text style={s.sub}>
          {data.memberName} · {data.workspaceName} · generated {data.generated} · framework: IRDAI-aligned conduct rubric (disclosure, no over-promising, needs-based advice)
        </Text>

        <View style={s.band}>
          <View style={s.stat}><Text style={s.statVal}>{data.ethicsAvg != null ? `${data.ethicsAvg}/100` : '—'}</Text><Text style={s.statLabel}>Ethics & compliance average</Text></View>
          <View style={s.stat}><Text style={data.flags > 0 ? [s.statVal, s.warn] : s.statVal}>{data.flags}</Text><Text style={s.statLabel}>Mis-selling flags raised</Text></View>
          <View style={s.stat}><Text style={s.statVal}>{data.scoredCalls}</Text><Text style={s.statLabel}>Scored calls (90 days)</Text></View>
        </View>

        <View style={s.th}>
          <Text style={[s.cDate, s.bold]}>Date</Text>
          <Text style={[s.cTitle, s.bold]}>Scenario</Text>
          <Text style={[s.cNum, s.bold]}>Overall</Text>
          <Text style={[s.cNum, s.bold]}>Ethics</Text>
          <Text style={[s.cFlag, s.bold]}>Conduct</Text>
        </View>
        {data.recent.map((r, i) => (
          <View key={i} style={s.tr}>
            <Text style={s.cDate}>{new Date(r.at).toLocaleDateString()}</Text>
            <Text style={s.cTitle}>{r.title}</Text>
            <Text style={s.cNum}>{Math.round(r.overall)}</Text>
            <Text style={s.cNum}>{r.ethics != null ? Math.round(r.ethics) : '—'}</Text>
            <Text style={r.flagged ? [s.cFlag, s.warn] : [s.cFlag, s.okTxt]}>{r.flagged ? 'FLAG' : 'Clear'}</Text>
          </View>
        ))}
        {data.recent.length === 0 && <Text style={{ color: '#71717a', marginTop: 8 }}>No scored calls in the reporting window.</Text>}

        <Text style={s.foot}>
          Flags are raised by the AI evaluator when a call contains over-promised returns, hidden exclusions/waiting periods, or pressure selling. Generated by SpeakCoach.
        </Text>
      </Page>
    </Document>
  );
}
