/**
 * Generate the client dossier (and a refined persona) for every public scenario.
 *
 *   npx tsx src/db/generate-briefs.ts             # all scenarios missing a brief
 *   npx tsx src/db/generate-briefs.ts --force     # regenerate everything
 *   npx tsx src/db/generate-briefs.ts --only "Term Life"   # one, by title match
 *   npx tsx src/db/generate-briefs.ts --dry       # print, write nothing
 *
 * Writes the brief to scenarios.client_brief AND emits
 * packages/shared/src/briefs.ts so a re-seed can restore it. The refined personas
 * are written to a review file rather than applied: they are hand-tuned, so a
 * human decides what lands in seed.ts.
 */
import fs from 'node:fs';
import path from 'node:path';
import { db } from '../config/database';
import { callAIService } from '../utils/ai-service-client';

const FORCE = process.argv.includes('--force');
const DRY = process.argv.includes('--dry');
const onlyIdx = process.argv.indexOf('--only');
const ONLY = onlyIdx > -1 ? process.argv[onlyIdx + 1] : null;

interface Row {
  id: string; title: string; description: string | null; objective: string | null;
  system_prompt: string; difficulty_level: string; language: string; client_brief: unknown;
}

async function main() {
  const where = ["deleted_at IS NULL", "visibility = 'public'", 'created_by IS NULL'];
  const params: unknown[] = [];
  if (!FORCE) where.push('client_brief IS NULL');
  if (ONLY) { params.push(`%${ONLY}%`); where.push(`title ILIKE $${params.length}`); }

  const res = await db.query(
    `SELECT id, title, description, objective, system_prompt, difficulty_level, language, client_brief
       FROM scenarios WHERE ${where.join(' AND ')} ORDER BY title`,
    params,
  );
  const rows = res.rows as Row[];
  console.log(`${rows.length} scenario(s) to process${DRY ? ' (dry run)' : ''}\n`);
  if (rows.length === 0) return;

  const briefs: Record<string, unknown> = {};
  const personas: { title: string; before: string; after: string; factDrift: string[] }[] = [];
  let leaks = 0;
  let drifted = 0;

  for (const [i, r] of rows.entries()) {
    process.stdout.write(`[${i + 1}/${rows.length}] ${r.title} … `);
    try {
      const aiRes = await callAIService({
        path: '/brief/generate',
        timeoutMs: 90_000,
        body: {
          title: r.title,
          description: r.description ?? '',
          objective: r.objective ?? '',
          persona: r.system_prompt,
          difficulty: r.difficulty_level,
          language: r.language,
        },
      });
      const out = await aiRes.json() as {
        brief: Record<string, unknown>; quiz: unknown; exchange: unknown;
        refined_prompt?: string; coaching_leak?: string[]; fact_drift?: string[];
      };

      const payload = { brief: out.brief, quiz: out.quiz, exchange: out.exchange };
      briefs[r.title] = payload;
      if (out.refined_prompt) {
        personas.push({ title: r.title, before: r.system_prompt, after: out.refined_prompt, factDrift: out.fact_drift ?? [] });
      }

      const notes: string[] = [];
      if (out.coaching_leak?.length) { leaks++; notes.push(`coaching: ${out.coaching_leak.join(', ')}`); }
      if (out.fact_drift?.length) { drifted++; notes.push(`persona facts changed: ${out.fact_drift.join(' ')}`); }
      console.log(notes.length ? `ok  ⚠ ${notes.join(' | ')}` : 'ok');

      if (!DRY) {
        await db.query('UPDATE scenarios SET client_brief = $2::jsonb, updated_at = NOW() WHERE id = $1',
          [r.id, JSON.stringify(payload)]);
      }
    } catch (err) {
      console.log(`FAILED: ${(err as Error).message}`);
    }
  }

  if (DRY) {
    console.log('\n--- sample ---');
    console.log(JSON.stringify(Object.values(briefs)[0], null, 2).slice(0, 2500));
    return;
  }

  // Commit the briefs so a re-seed restores them.
  const sharedPath = path.resolve(__dirname, '../../../../packages/shared/src/briefs.ts');
  const existing = fs.existsSync(sharedPath) ? readExisting(sharedPath) : {};
  const merged = { ...existing, ...briefs };
  fs.writeFileSync(sharedPath,
    `/**\n * Client dossiers, keyed by scenario title.\n *\n * GENERATED by apps/api/src/db/generate-briefs.ts. Edit by regenerating, or by\n * hand if you are fixing one line. The seed writes these into scenarios.client_brief,\n * so re-seeding never loses them.\n */\nimport type { ScenarioBrief } from './brief';\n\nexport const SCENARIO_BRIEFS: Record<string, ScenarioBrief> = ${JSON.stringify(merged, null, 2)} as unknown as Record<string, ScenarioBrief>;\n`,
    'utf-8');
  console.log(`\nwrote ${Object.keys(merged).length} briefs -> packages/shared/src/briefs.ts`);

  // Refined personas go to a review file: seed.ts is hand-tuned, a human merges.
  if (personas.length) {
    const reviewPath = path.resolve(__dirname, 'refined-personas.review.json');
    fs.writeFileSync(reviewPath, JSON.stringify(personas, null, 2), 'utf-8');
    console.log(`wrote ${personas.length} refined personas -> ${path.basename(reviewPath)} (review before merging into seed.ts)`);
  }
  if (leaks) console.log(`\n⚠ ${leaks} brief(s) still contain coaching language. Re-run --force --only "<title>" or fix by hand.`);
  if (drifted) console.log(`⚠ ${drifted} refined persona(s) changed a number the original stated. They are NOT applied; review the file before merging any into seed.ts.`);
}

function readExisting(file: string): Record<string, unknown> {
  const src = fs.readFileSync(file, 'utf-8');
  const start = src.indexOf('= {');
  const end = src.lastIndexOf('} as unknown');
  if (start === -1 || end === -1) return {};
  try { return JSON.parse(src.slice(start + 2, end + 1)); } catch { return {}; }
}

main()
  .then(() => process.exit(0))
  .catch((err) => { console.error(err); process.exit(1); });
