/**
 * The prompts ARE the product. Retyping them into TypeScript is how you get a
 * silent one-word drift that nobody notices until scores move, so they are
 * lifted straight out of the Python — by Python's own parser, which already
 * knows about triple quotes, single quotes, adjacent-literal concatenation and
 * escapes. A regex here got two of eight subtly wrong.
 *
 * Run: node scripts/extract-prompts.mjs   (then: node --test test/prompts.test.mjs)
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const ROUTES = '../ai-service/src/routes/';
const WANT = [
  ['PROMPT_SYSTEM', 'prompt.py', '_SYSTEM'],
  ['DRILL_SYSTEM', 'drill.py', '_SYSTEM'],
  ['NOTES_SYSTEM', 'notes.py', '_SYSTEM'],
  ['BRIEF_SYSTEM', 'brief.py', '_SYSTEM'],
  ['PLAN_SYSTEM', 'plan.py', '_SYSTEM'],
  ['SCENARIO_SYSTEM', 'scenario.py', '_SYSTEM'],
  ['SCENARIO_STAY_IN_CHARACTER', 'scenario.py', '_STAY_IN_CHARACTER'],
  ['SPEECH_SYSTEM', 'speech.py', '_SYSTEM'],
  ['EVALUATION_SYSTEM', '../core/scoring.py', 'EVALUATION_SYSTEM_PROMPT'],
  ['BEGINNER_RUBRIC', '../core/scoring.py', 'BEGINNER_RUBRIC'],
  ['INTERMEDIATE_RUBRIC', '../core/scoring.py', 'INTERMEDIATE_RUBRIC'],
  ['ADVANCED_RUBRIC', '../core/scoring.py', 'ADVANCED_RUBRIC'],
];

const PY = `
import ast, sys, json
tree = ast.parse(open(sys.argv[1]).read())
for node in tree.body:
    if isinstance(node, ast.Assign) and getattr(node.targets[0], 'id', None) == sys.argv[2]:
        print(json.dumps(ast.literal_eval(node.value)))
        break
`;

const out = [
  '// GENERATED by scripts/extract-prompts.mjs — do not edit.',
  '// Lifted verbatim from apps/ai-service/src/routes/*.py so the wording cannot',
  '// drift during the port. Re-run the script when a Python prompt changes;',
  '// test/prompts.test.mjs fails if the two ever disagree.',
  '',
];

for (const [name, file, constant] of WANT) {
  const raw = execFileSync('python3', ['-c', PY, ROUTES + file, constant], { encoding: 'utf8' }).trim();
  if (!raw) throw new Error(`${file}:${constant} not found`);
  const value = JSON.parse(raw);
  out.push(`export const ${name} = ${JSON.stringify(value)};`, '');
  console.log(`  ${name.padEnd(28)} ${String(value.length).padStart(5)} chars  <- ${file}:${constant}`);
}

writeFileSync('src/prompts.ts', out.join('\n'));
console.log(`\nwrote src/prompts.ts (${WANT.length} prompts)`);
