import puppeteer from 'puppeteer';
import { logger } from '../config/logger';

interface CriteriaScore {
  criterion_name: string;
  score: number;
  weight: number;
  justification: string;
}

interface TranscriptItem {
  turn_number: number;
  role: string;
  content: string;
  duration_ms: number;
  created_at: string | Date;
}

interface ReportData {
  overall_score: number;
  criteria_scores: CriteriaScore[];
  strengths: string[];
  improvements: string[];
  narrative_feedback: string;
  scored_by_model: string;
  scored_at: string | Date;
  duration_sec: number;
  total_turns: number;
  started_at: string | Date;
  ended_at: string | Date;
  scenario_title: string;
  scoring_rubric: any;
  objective: string;
  persona_name: string;
  learner_name: string;
  learner_email: string;
  tenant_name: string;
}

interface GenerateReportOptions {
  report: ReportData;
  transcript: TranscriptItem[];
  sessionId: string;
}

export class PDFService {
  static async generateReport(options: GenerateReportOptions): Promise<Buffer> {
    const { report, transcript, sessionId } = options;

    logger.info({ sessionId }, 'Generating PDF report');

    const html = PDFService.buildHTML(report, transcript, sessionId);

    let browser;
    try {
      browser = await puppeteer.launch({ headless: true });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '60px',
          bottom: '60px',
          left: '40px',
          right: '40px',
        },
        displayHeaderFooter: true,
        headerTemplate: '<span></span>',
        footerTemplate: `
          <div style="width: 100%; font-size: 9px; font-family: system-ui, -apple-system, sans-serif; color: #9ca3af; padding: 0 40px; display: flex; justify-content: space-between; align-items: center;">
            <span>Generated by AI Avatar Training Platform</span>
            <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `,
      });

      logger.info({ sessionId, size: pdfBuffer.length }, 'PDF report generated successfully');

      return Buffer.from(pdfBuffer);
    } catch (err) {
      logger.error({ sessionId, err }, 'Failed to generate PDF report');
      throw err;
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  private static getScoreColor(score: number): string {
    if (score >= 80) return '#22c55e';
    if (score >= 60) return '#eab308';
    return '#ef4444';
  }

  private static formatDate(date: string | Date): string {
    const d = new Date(date);
    return d.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  private static formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    if (mins === 0) return `${secs}s`;
    return `${mins}m ${secs}s`;
  }

  private static escapeHtml(text: string): string {
    if (!text) return '';
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private static buildHTML(
    report: ReportData,
    transcript: TranscriptItem[],
    sessionId: string,
  ): string {
    const scoreColor = PDFService.getScoreColor(report.overall_score);

    const criteriaRows = (report.criteria_scores || [])
      .map(
        (c) => `
        <tr>
          <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-weight: 500;">
            ${PDFService.escapeHtml(c.criterion_name)}
          </td>
          <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">
            ${Math.round(c.weight)}%
          </td>
          <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">
            <span style="color: ${PDFService.getScoreColor((c.score / 5) * 100)}; font-weight: 700;">${c.score}/5</span>
          </td>
          <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; color: #4b5563;">
            ${PDFService.escapeHtml(c.justification)}
          </td>
        </tr>`,
      )
      .join('');

    const strengthsList = (report.strengths || [])
      .map(
        (s) => `
        <li style="margin-bottom: 8px; padding-left: 4px;">
          <span style="color: #22c55e; margin-right: 6px;">&#10003;</span>
          ${PDFService.escapeHtml(s)}
        </li>`,
      )
      .join('');

    const improvementsList = (report.improvements || [])
      .map(
        (i) => `
        <li style="margin-bottom: 8px; padding-left: 4px;">
          <span style="color: #f97316; margin-right: 6px;">&#10148;</span>
          ${PDFService.escapeHtml(i)}
        </li>`,
      )
      .join('');

    const transcriptRows = (transcript || [])
      .map(
        (t, idx) => `
        <tr style="background-color: ${idx % 2 === 0 ? '#ffffff' : '#f9fafb'};">
          <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb; text-align: center; font-size: 13px; color: #6b7280;">
            ${t.turn_number}
          </td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">
            <span style="
              display: inline-block;
              padding: 2px 10px;
              border-radius: 12px;
              font-size: 12px;
              font-weight: 600;
              ${t.role === 'learner' ? 'background-color: #dbeafe; color: #1d4ed8;' : 'background-color: #f3e8ff; color: #7c3aed;'}
            ">${PDFService.escapeHtml(t.role)}</span>
          </td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; line-height: 1.5;">
            ${PDFService.escapeHtml(t.content)}
          </td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; white-space: nowrap;">
            ${PDFService.formatDate(t.created_at)}
          </td>
        </tr>`,
      )
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: system-ui, -apple-system, sans-serif;
      color: #1f2937;
      font-size: 14px;
      line-height: 1.6;
    }

    .page-section {
      page-break-inside: avoid;
      margin-bottom: 28px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    h2 {
      font-size: 18px;
      font-weight: 700;
      color: #111827;
      margin-bottom: 12px;
      padding-bottom: 6px;
      border-bottom: 2px solid #e5e7eb;
    }

    .header {
      text-align: center;
      padding: 24px 0 20px;
      border-bottom: 3px solid #3b82f6;
      margin-bottom: 28px;
    }

    .header .tenant-name {
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 2px;
      color: #6b7280;
      margin-bottom: 6px;
    }

    .header h1 {
      font-size: 26px;
      font-weight: 800;
      color: #111827;
      margin-bottom: 4px;
    }

    .header .date {
      font-size: 13px;
      color: #9ca3af;
    }

    .score-section {
      display: flex;
      align-items: flex-start;
      gap: 32px;
      padding: 20px;
      background: #f9fafb;
      border-radius: 8px;
      margin-bottom: 28px;
      page-break-inside: avoid;
    }

    .score-circle {
      flex-shrink: 0;
      width: 110px;
      height: 110px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 42px;
      font-weight: 800;
      color: #ffffff;
    }

    .score-meta {
      flex: 1;
    }

    .score-meta .meta-row {
      display: flex;
      justify-content: space-between;
      padding: 5px 0;
      border-bottom: 1px solid #e5e7eb;
      font-size: 13px;
    }

    .score-meta .meta-row .label {
      color: #6b7280;
    }

    .score-meta .meta-row .value {
      font-weight: 600;
      color: #1f2937;
    }

    .two-col {
      display: flex;
      gap: 24px;
      margin-bottom: 28px;
      page-break-inside: avoid;
    }

    .two-col .col {
      flex: 1;
      padding: 16px;
      border-radius: 8px;
    }

    .two-col .col.strengths {
      background: #f0fdf4;
      border: 1px solid #bbf7d0;
    }

    .two-col .col.improvements {
      background: #fff7ed;
      border: 1px solid #fed7aa;
    }

    .two-col .col h3 {
      font-size: 15px;
      font-weight: 700;
      margin-bottom: 10px;
    }

    .two-col .col ul {
      list-style: none;
      padding: 0;
      font-size: 13px;
    }

    .narrative {
      padding: 16px 20px;
      background: #f9fafb;
      border-left: 4px solid #3b82f6;
      border-radius: 4px;
      font-size: 14px;
      line-height: 1.7;
      color: #374151;
      margin-bottom: 28px;
      page-break-inside: avoid;
    }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="header">
    <div class="tenant-name">${PDFService.escapeHtml(report.tenant_name)}</div>
    <h1>Training Session Report</h1>
    <div class="date">${PDFService.formatDate(report.scored_at)}</div>
  </div>

  <!-- Score Summary -->
  <div class="score-section">
    <div class="score-circle" style="background-color: ${scoreColor};">
      ${Math.round(report.overall_score)}
    </div>
    <div class="score-meta">
      <div class="meta-row">
        <span class="label">Learner</span>
        <span class="value">${PDFService.escapeHtml(report.learner_name)} (${PDFService.escapeHtml(report.learner_email)})</span>
      </div>
      <div class="meta-row">
        <span class="label">Scenario</span>
        <span class="value">${PDFService.escapeHtml(report.scenario_title)}</span>
      </div>
      <div class="meta-row">
        <span class="label">Persona</span>
        <span class="value">${PDFService.escapeHtml(report.persona_name)}</span>
      </div>
      <div class="meta-row">
        <span class="label">Date</span>
        <span class="value">${PDFService.formatDate(report.started_at)}</span>
      </div>
      <div class="meta-row">
        <span class="label">Duration</span>
        <span class="value">${PDFService.formatDuration(report.duration_sec)}</span>
      </div>
      <div class="meta-row">
        <span class="label">Total Turns</span>
        <span class="value">${report.total_turns}</span>
      </div>
      <div class="meta-row">
        <span class="label">Session ID</span>
        <span class="value" style="font-size: 11px; font-family: monospace;">${PDFService.escapeHtml(sessionId)}</span>
      </div>
    </div>
  </div>

  <!-- Criteria Scores Table -->
  <div class="page-section">
    <h2>Scoring Criteria</h2>
    <table>
      <thead>
        <tr style="background-color: #f3f4f6;">
          <th style="padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">Criterion</th>
          <th style="padding: 10px 12px; text-align: center; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">Weight</th>
          <th style="padding: 10px 12px; text-align: center; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">Score</th>
          <th style="padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">Justification</th>
        </tr>
      </thead>
      <tbody>
        ${criteriaRows}
      </tbody>
    </table>
  </div>

  <!-- Strengths & Improvements -->
  <div class="two-col">
    <div class="col strengths">
      <h3 style="color: #15803d;">Strengths</h3>
      <ul>${strengthsList}</ul>
    </div>
    <div class="col improvements">
      <h3 style="color: #c2410c;">Areas for Improvement</h3>
      <ul>${improvementsList}</ul>
    </div>
  </div>

  <!-- Narrative Feedback -->
  <div class="page-section">
    <h2>Narrative Feedback</h2>
    <div class="narrative">
      ${PDFService.escapeHtml(report.narrative_feedback)}
    </div>
  </div>

  <!-- Full Transcript -->
  <div class="page-section">
    <h2>Full Transcript</h2>
    <table>
      <thead>
        <tr style="background-color: #f3f4f6;">
          <th style="padding: 8px 12px; text-align: center; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb; width: 50px;">Turn</th>
          <th style="padding: 8px 12px; text-align: center; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb; width: 90px;">Role</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">Content</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; border-bottom: 2px solid #e5e7eb; width: 140px;">Timestamp</th>
        </tr>
      </thead>
      <tbody>
        ${transcriptRows}
      </tbody>
    </table>
  </div>

</body>
</html>`;
  }
}
