/** The curriculum spine: units -> ordered lessons, each lesson = one seeded
 *  scenario (referenced by title — the seed is idempotent on title). Static by
 *  design (ponytail: curriculum is content, not data — no tables, no admin UI;
 *  edit this file to change the path). Progress is computed at read time from
 *  sessions + session_scores, so there is nothing to migrate or sync. */

export interface JourneyLesson {
  key: string;       // stable id, e.g. 'opening-1'
  scenario: string;  // seed scenario title (exact match)
}

export interface WatchLine { speaker: 'agent' | 'customer'; text: string }

export interface QuizOption { id: string; title: string; text: string }
export interface UnitQuiz {
  client: { role: string; focus: string; pain: string };
  question: string;
  hint: string;
  options: QuizOption[];
  correct: string;       // option id
  why: string;           // one-line rationale for the correct pick
  whyBullets: string[];  // 2-3 reasons it works
}

export interface JourneyUnit {
  key: string;
  title: string;
  drills: string;    // what this unit teaches, one line
  do: string[];      // briefing: what to do (the technique)
  dont: string[];    // briefing: the traps
  /** Learn card (~60s read): the unit's technique, markdown. Free forever. */
  learn: string;
  /** Watch: a short model call demonstrating the technique. Audio generated by
   *  scripts from this dialogue (public/watch/{unit}.wav + .json captions). */
  watchScript: WatchLine[];
  /** Index into watchScript of the line that IS the technique ("spot it"). */
  spot: number;
  spotNote: string;
  /** "Your Turn" knowledge check — free, between Watch and Practice. */
  quiz: UnitQuiz;
  lessons: JourneyLesson[];
}

export const JOURNEY_MINUTES = 10; // nominal module length shown in the header

/** Mastery thresholds on best overall score (0-100). */
export const MASTERY = { bronze: 50, silver: 70, gold: 85 } as const;
export type Mastery = 'none' | 'bronze' | 'silver' | 'gold';

/**
 * The pass mark. At or above it a scenario counts as COMPLETED: it leaves the
 * learner's Scenarios list and lands on Completed. Below the fail mark the attempt
 * counts as FAILED and the scenario stays in Scenarios to be retried.
 *
 * Deliberately the existing mastery cutoffs rather than two new numbers, so a
 * silver crown and "completed" can never disagree.
 */
export const PASS_MARK = MASTERY.silver;   // 70
export const FAIL_MARK = MASTERY.bronze;   // below 50 is a fail

/** completed = green · attempted = yellow · failed = red · none = never tried. */
export type Grade = 'completed' | 'attempted' | 'failed' | 'none';

export const GRADE_LABEL: Record<Grade, string> = {
  completed: 'Completed',
  attempted: 'Attempted',
  failed: 'Failed',
  none: 'Not tried',
};

/**
 * Grade a scenario from the learner's BEST score on it, not their latest: one bad
 * run after a good one must not un-complete something they have already proved.
 * `attempts` distinguishes "never tried" from "tried and scored nothing".
 */
export function gradeFor(best: number | null, attempts = 0): Grade {
  if (best == null) return attempts > 0 ? 'failed' : 'none';
  if (best >= PASS_MARK) return 'completed';
  if (best >= FAIL_MARK) return 'attempted';
  return 'failed';
}

export function masteryFor(best: number | null): Mastery {
  if (best == null) return 'none';
  if (best >= MASTERY.gold) return 'gold';
  if (best >= MASTERY.silver) return 'silver';
  if (best >= MASTERY.bronze) return 'bronze';
  return 'none';
}

export const JOURNEY: JourneyUnit[] = [
  {
    key: 'opening', title: 'The Opening',
    drills: 'Earning the first thirty seconds — getting past "I\'m busy" and "not interested".',
    do: [
      'Respect their time out loud ("sixty seconds, then cut me off")',
      'Give a hook that is about THEIR situation, not your product',
      'Ask permission to continue — and mean it',
    ],
    dont: [
      'Launch into a pitch before they agree to listen',
      'Push harder after a brush-off — that ends calls',
      'Sound like a script; they can hear it',
    ],
    learn: `**The 30-second rule.** A cold customer decides in half a minute whether you are worth hearing — before any product is mentioned.

1. **Name the time cost up front.** "Sixty seconds, then cut me off." Handing over control is what disarms.
2. **Hook = THEIR situation.** Their shop, their loan, their kids — never your product.
3. **End the opener with permission.** "May I?" A person who says "okay, one minute" has *chosen* to listen — everything after that goes differently.`,
    watchScript: [
      { speaker: 'customer', text: 'Hello? Who is this? I am busy.' },
      { speaker: 'agent', text: 'Sir, Ravi from SecureLife — give me sixty seconds, and if it is not useful, cut me off.' },
      { speaker: 'customer', text: 'Hm. Okay. Sixty seconds.' },
      { speaker: 'agent', text: 'You took a home loan last year, right? If anything happens to you, that EMI lands on your family. That is the only thing I want to talk about.' },
      { speaker: 'customer', text: 'Okay... that I do think about sometimes.' },
      { speaker: 'agent', text: 'Two minutes now, or should I call after your shop closes?' },
      { speaker: 'customer', text: 'No, go ahead, tell me now.' },
    ],
    spot: 1,
    spotNote: 'Names the time cost and hands over control — that is what buys the next minute.',
    quiz: {
      client: { role: 'Busy shop owner', focus: 'Running his store, no patience', pain: 'Gets five sales calls a day and hangs up on all of them' },
      question: 'How do you earn the first sixty seconds?',
      hint: 'The best opener is about HIM, and hands him control.',
      options: [
        { id: 'A', title: 'Straight to the pitch', text: '"Sir, I have an excellent term plan I want to tell you about."' },
        { id: 'B', title: 'Time-boxed + their situation', text: '"Sixty seconds — cut me off if it is not useful. It is about the loan on your shop."' },
        { id: 'C', title: 'Flattery', text: '"You sound like a smart man, sir, you will really appreciate this."' },
        { id: 'D', title: 'Guilt', text: '"Please just give me two minutes, I have been trying to reach you all week."' },
      ],
      correct: 'B',
      why: 'Handing over control and tying the call to his loan disarms the reflex to hang up.',
      whyBullets: ['Respects his time out loud', 'The hook is about HIM, not your product', 'Lets him choose to keep listening'],
    },
    lessons: [
      { key: 'opening-1', scenario: 'Home Insurance — Post-Disaster Call' },
      { key: 'opening-2', scenario: 'Crop Insurance — Skeptical Farmer' },
      { key: 'opening-3', scenario: 'Cyber Insurance — Digital Retailer' },
      { key: 'opening-4', scenario: 'Term Life — Cold Call' },
    ],
  },
  {
    key: 'discovery', title: 'Discovery',
    drills: 'Needs-based questioning — understand before you sell (the foundation of compliant advice).',
    do: [
      'Ask about family, income, dependants and existing cover BEFORE any product talk',
      'Follow up on their answers — one good probe beats five questions',
      'Let silence work; people fill it with the truth',
    ],
    dont: [
      'Pitch in your first three turns',
      'Interrogate — it is a conversation, not a form',
      'Assume the need; surface it',
    ],
    learn: `**Sell nothing yet.** Discovery is where the call is actually won — and it is also what makes advice compliant: you cannot mis-sell what you matched to a stated need.

1. **Family, income, dependants, existing cover — before any product word.**
2. **One good probe beats five questions.** "How long ago was that?" goes deeper than a new topic.
3. **Let silence work.** Count two beats after their answer; people fill silence with the real story.

What you learn here writes your pitch for you.`,
    watchScript: [
      { speaker: 'agent', text: 'Before I suggest anything — who all depend on your income right now?' },
      { speaker: 'customer', text: 'Wife, two kids. My mother also stays with us.' },
      { speaker: 'agent', text: 'And if that income stopped for six months... what happens?' },
      { speaker: 'customer', text: 'Honestly? We would be in trouble by month two.' },
      { speaker: 'agent', text: 'Then that is what we fix first. Do you have any cover today?' },
      { speaker: 'customer', text: 'One LIC policy from years ago. I do not even know what it covers.' },
      { speaker: 'agent', text: 'Most people do not — let us find out what you have before we add anything new.' },
    ],
    spot: 2,
    spotNote: 'Probes the consequence, not the fact — that is where the real need surfaces.',
    quiz: {
      client: { role: 'Salaried father of two', focus: 'Careful with money', pain: 'Has an old policy he does not understand, unsure what he needs' },
      question: 'Which question best uncovers his real need?',
      hint: 'Surface the consequence, not just a fact.',
      options: [
        { id: 'A', title: 'Product-first', text: '"Would you like a one-crore term plan today?"' },
        { id: 'B', title: 'Closed fact', text: '"Do you have life insurance?"' },
        { id: 'C', title: 'Consequence probe', text: '"If your income stopped for six months, what would happen to the family?"' },
        { id: 'D', title: 'Budget-first', text: '"What is your monthly budget for insurance?"' },
      ],
      correct: 'C',
      why: 'Making him picture the consequence surfaces the real need — far more than a yes/no fact.',
      whyBullets: ['Gets past "I already have something"', 'Makes the risk feel real, not abstract', 'His own words become your pitch'],
    },
    lessons: [
      { key: 'discovery-1', scenario: 'Child Education Plan' },
      { key: 'discovery-2', scenario: 'Shopkeeper Package — Multi-Peril Retail' },
      { key: 'discovery-3', scenario: 'Family Term Plan — Young Parent' },
      { key: 'discovery-4', scenario: 'Group Health Insurance — SME Pitch' },
    ],
  },
  {
    key: 'pitch', title: 'The Pitch',
    drills: 'Matching the product to a stated need — selling value, not features.',
    do: [
      'Tie every benefit to something THEY said',
      'Use one relatable example instead of three statistics',
      'Explain in their words; check they understood',
    ],
    dont: [
      'Feature-dump — nobody buys a list',
      'Use jargon they never asked about',
      'Oversell; a modest true claim beats a grand vague one',
    ],
    learn: `**Their words, your product.** A pitch lands only when it is an *answer* to something they said.

1. **The formula:** "You said X. This does Y about X." If a feature does not connect to something they said — do not say it.
2. **One relatable example beats three statistics.** "Eight hundred a month — one restaurant bill — covers the whole loan."
3. **Check understanding.** "Does that make sense for your situation?" An unchecked pitch is a monologue.`,
    watchScript: [
      { speaker: 'customer', text: 'So what is this plan exactly?' },
      { speaker: 'agent', text: 'You told me your real worry is Aanya’s college in fourteen years. This plan locks a guaranteed amount for exactly that year — whatever the markets do, that number does not move.' },
      { speaker: 'customer', text: 'Guaranteed meaning... fixed?' },
      { speaker: 'agent', text: 'Fixed. Like an FD, but it forces the discipline monthly, and adds life cover on you till then.' },
      { speaker: 'customer', text: 'And if something happens to me in between?' },
      { speaker: 'agent', text: 'The premiums stop, and the college amount stays. That is the whole point of it being an education plan and not just savings.' },
    ],
    spot: 1,
    spotNote: 'Every line starts from what the customer said — the product is framed purely as the answer.',
    quiz: {
      client: { role: 'Father of a young daughter', focus: 'Her education', pain: 'Told you he is worried about affording college in 14 years' },
      question: 'Which pitch will land?',
      hint: 'Connect the product to the exact thing he told you.',
      options: [
        { id: 'A', title: 'Feature dump', text: '"It has guaranteed maturity, tax benefit, life cover, and flexible premiums."' },
        { id: 'B', title: 'Tied to his goal', text: '"You said college in 14 years is the worry — this locks a guaranteed amount for exactly that year."' },
        { id: 'C', title: 'Generic benefit', text: '"Insurance is very important for every family these days."' },
        { id: 'D', title: 'Returns-led', text: '"You could get great returns if the market does well."' },
      ],
      correct: 'B',
      why: 'It frames the product as the direct answer to the exact worry he stated — instant relevance.',
      whyBullets: ['Anchored to HIS stated goal', 'One clear idea, not a feature list', 'No over-promise'],
    },
    lessons: [
      { key: 'pitch-1', scenario: 'Savings / Endowment Plan — Maturity & Tax' },
      { key: 'pitch-2', scenario: 'Restaurant Public Liability' },
      { key: 'pitch-3', scenario: 'Marine Cargo — Export Transit Cover' },
      { key: 'pitch-4', scenario: 'Keyman Insurance — B2B SME Pitch' },
    ],
  },
  {
    key: 'objections', title: 'Objection Handling',
    drills: '"Too expensive", "I already have a policy", "let me think" — validate, then resolve.',
    do: [
      'Acknowledge the objection as reasonable before answering it',
      'Answer the REAL concern underneath, not just the words',
      'Trade value for value — never just discount',
    ],
    dont: [
      'Argue or get defensive — you lose even if you win',
      'Fold at the first pushback',
      'Ignore it and repeat the pitch louder',
    ],
    learn: `**Agree first, answer second.** An objection fought is an objection strengthened.

1. **Validate:** "You are right to ask that." It costs nothing and lowers the guard.
2. **Find the real concern underneath.** "Too expensive" usually means "not worth it *yet*". Ask which it is.
3. **Answer THAT — with proof or a story, never a discount.** Trade value, not price.

And when they are right? Say so. Honesty converts better than victory.`,
    watchScript: [
      { speaker: 'customer', text: 'Fifteen thousand a year is just too much.' },
      { speaker: 'agent', text: 'Fair — it is real money. Can I ask what feels heavy: the amount itself, or paying for something you might never use?' },
      { speaker: 'customer', text: 'The second one, honestly. I am healthy.' },
      { speaker: 'agent', text: 'Then here is the number that changed my mind: one night in a city ICU is about forty thousand. This is one-third of one night, per year, for unlimited nights.' },
      { speaker: 'customer', text: 'Hm. When you put it that way...' },
      { speaker: 'agent', text: 'And if you never claim, your cover grows every year as a bonus. Healthy is exactly when this is cheap.' },
    ],
    spot: 1,
    spotNote: 'Splits the stated objection from the real one before answering anything.',
    quiz: {
      client: { role: 'Young, healthy professional', focus: 'Saving for a house', pain: 'Says health cover is "too expensive" for someone who never gets sick' },
      question: 'What is your best first move on "too expensive"?',
      hint: 'Agree first, then find what is really underneath.',
      options: [
        { id: 'A', title: 'Argue the price', text: '"It is actually very cheap compared to other companies."' },
        { id: 'B', title: 'Discount', text: '"Let me see if I can get you a lower premium."' },
        { id: 'C', title: 'Validate + split', text: '"Fair, it is real money. Is it the amount, or paying for something you might never use?"' },
        { id: 'D', title: 'Scare tactic', text: '"One hospital visit could bankrupt you, you know."' },
      ],
      correct: 'C',
      why: 'Validating lowers the guard, and splitting the objection tells you which concern to actually answer.',
      whyBullets: ['Never argue an objection', 'Finds the real concern under "too expensive"', 'Sets up a value answer, not a discount'],
    },
    lessons: [
      { key: 'objections-1', scenario: 'Critical Illness — Exclusion Concern' },
      { key: 'objections-2', scenario: 'Health Insurance — Price Objection' },
      { key: 'objections-3', scenario: 'Retirement Annuity vs. Fixed Deposit' },
    ],
  },
  {
    key: 'compliance', title: 'Compliance & Ethics',
    drills: 'Disclosures, exclusions, no over-promised returns — selling that survives an audit.',
    do: [
      'State waiting periods, exclusions and charges up front',
      'When tempted with "so it\'s guaranteed, right?" — correct it clearly',
      'Recommend LESS when less is what fits',
    ],
    dont: [
      'Promise or imply guaranteed returns on market products',
      'Hide the fine print until after the yes',
      'Sell a product that does not fit the need',
    ],
    learn: `**Sell like the audit is listening.** In insurance, the two fastest ways to lose everything are over-promised returns and hidden exclusions.

1. **Disclose before the yes.** Waiting periods, exclusions, charges — up front, in plain words.
2. **Correct the "guaranteed?" ask clearly.** The customer's excitement is not consent. "Twelve percent is possible; zero years happen too."
3. **Recommend less when less fits.** One honest "no" sells the next three policies.

IRDAI rules are not the ceiling of ethics — they are the floor.`,
    watchScript: [
      { speaker: 'customer', text: 'My friend said I will get twelve percent guaranteed, right?' },
      { speaker: 'agent', text: 'I have to stop you there — no. This is market-linked. Twelve percent is possible; zero years happen too. Nobody can guarantee it, and anyone who does is misleading you.' },
      { speaker: 'customer', text: 'Oh. Then why would I take it at all?' },
      { speaker: 'agent', text: 'Long horizon, tax benefit, and life cover — but only if you are comfortable with the ups and downs. If you want guaranteed, I would honestly point you to a different product.' },
      { speaker: 'customer', text: 'You are the first agent who has said that to me.' },
      { speaker: 'agent', text: 'That is the only way I work. Let us figure out which one actually fits you.' },
    ],
    spot: 1,
    spotNote: 'Corrects the guarantee ask directly — giving up the easy yes to keep the truth.',
    quiz: {
      client: { role: 'Eager first-time investor', focus: 'High returns', pain: 'A friend told him a ULIP gives "guaranteed 12%" and he wants you to confirm it' },
      question: 'He asks "so it is guaranteed 12%, right?" — what do you say?',
      hint: 'His excitement is not consent. The audit is listening.',
      options: [
        { id: 'A', title: 'Confirm it', text: '"Yes sir, around 12% every year."' },
        { id: 'B', title: 'Dodge', text: '"Returns are usually very good, do not worry about it."' },
        { id: 'C', title: 'Correct it clearly', text: '"I have to stop you — no. It is market-linked. 12% is possible; zero years happen too."' },
        { id: 'D', title: 'Soft-pedal', text: '"Almost guaranteed, historically it has done well."' },
      ],
      correct: 'C',
      why: 'Correcting the guarantee is non-negotiable — implying it is mis-selling, no matter how much he wants to hear it.',
      whyBullets: ['Compliant and honest', 'His excitement is not consent', 'Builds trust that closes the NEXT sale'],
    },
    lessons: [
      { key: 'compliance-1', scenario: 'ULIP / Investment Plan — Confused Customer' },
      { key: 'compliance-2', scenario: 'Senior Citizen Health Plan — Trust & Clarity' },
      { key: 'compliance-3', scenario: 'Credit-Linked Cover — Loan Protection' },
    ],
  },
  {
    key: 'closing', title: 'Closing',
    drills: 'Asking for the sale, handling the final hesitation, locking a real next step.',
    do: [
      'Ask clearly for a specific commitment with a date',
      'Make the next step small and easy to say yes to',
      'Surface the real hesitation behind "I\'ll think about it"',
    ],
    dont: [
      'Pressure or fake urgency — it reads as desperation',
      'Accept a vague "maybe" as a close',
      'Keep selling after they have already said yes',
    ],
    learn: `**Ask, small and specific.** Deals do not die dramatically — they die politely, inside "I'll think about it."

1. **Make the next step tiny and dated.** "I'll send the form now — shall we fill it Sunday at six?"
2. **Surface the doubt behind the stall.** "Happy to give you time — what is the one thing you are still weighing?"
3. **Never accept a vague maybe.** Convert it into a real objection (handle it) or a real commitment (book it).

And the moment they say yes — stop selling.`,
    watchScript: [
      { speaker: 'customer', text: 'It sounds decent. Let me think about it.' },
      { speaker: 'agent', text: 'Of course. Just so I leave you with the right thing to think about — what is the one part you are still weighing?' },
      { speaker: 'customer', text: 'Whether the premium fits this year, honestly.' },
      { speaker: 'agent', text: 'Then let us solve that: we can start at ten lakh cover now and step it up next year. A small start beats no start.' },
      { speaker: 'customer', text: 'That... actually works.' },
      { speaker: 'agent', text: 'Then I will send the form now — five minutes together on Sunday at six, and you are covered by Monday?' },
      { speaker: 'customer', text: 'Okay. Sunday, six o’clock.' },
    ],
    spot: 1,
    spotNote: 'Turns "I’ll think about it" into the actual objection — then closes on a small, dated step.',
    quiz: {
      client: { role: 'Interested but hesitant prospect', focus: 'Wants to feel sure', pain: 'Says "it sounds decent, let me think about it"' },
      question: 'How do you handle "let me think about it"?',
      hint: 'A vague maybe is not a close. Surface the real doubt.',
      options: [
        { id: 'A', title: 'Accept it', text: '"Sure, take your time and call me whenever."' },
        { id: 'B', title: 'Pressure', text: '"This offer is only valid today, so decide now."' },
        { id: 'C', title: 'Surface + shrink', text: '"Of course — what is the one thing you are still weighing?" then propose a small, dated first step.' },
        { id: 'D', title: 'Repeat the pitch', text: '"Let me explain all the benefits one more time."' },
      ],
      correct: 'C',
      why: 'It converts a polite stall into the real objection you can handle, and closes on a tiny, dated commitment.',
      whyBullets: ['Finds the true hesitation', 'A small dated step beats a vague maybe', 'No fake urgency'],
    },
    lessons: [
      { key: 'closing-1', scenario: 'Motor Insurance — Renewal + Add-ons' },
      { key: 'closing-2', scenario: 'Group Health Renewal — Copay Dispute' },
      { key: 'closing-3', scenario: 'Follow-up Close — "I will think about it"' },
      { key: 'closing-4', scenario: 'Directors & Officers (D&O) — Series A CEO' },
    ],
  },
  {
    key: 'service', title: 'Renewals & Service',
    drills: 'The angry renewal and the worried claimant — keeping trust when it is hardest.',
    do: [
      'Let them vent fully before you explain anything',
      'Acknowledge loyalty and feelings explicitly',
      'Resolve first; only earn the right to sell after',
    ],
    dont: [
      'Get defensive about the company',
      'Cross-sell to someone who is still upset',
      'Hide behind policy language',
    ],
    learn: `**Vent first, facts second.** An angry customer is not asking for information — they are asking to be heard.

1. **Let them finish. Completely.** No interruptions, no "but sir".
2. **Acknowledge the feeling AND the loyalty.** "Ten years with us, and the renewal feels like this — I would be angry too."
3. **Only then explain, in plain words.** And only if the moment truly settles do you earn the right to suggest anything.

A customer who felt heard renews. One who was "handled" leaves quietly next year.`,
    watchScript: [
      { speaker: 'customer', text: 'No claims. Not one. And my premium goes UP? This is cheating!' },
      { speaker: 'agent', text: 'You are right to be angry — and after this many years with us, you deserve a straight answer, not a script.' },
      { speaker: 'customer', text: 'Then give me one!' },
      { speaker: 'agent', text: 'Two things moved: the government revised third-party rates, and your car’s parts got costlier to repair. Neither is about your driving — your record actually earned a discount that is already applied.' },
      { speaker: 'customer', text: 'So without my record it would be even worse?' },
      { speaker: 'agent', text: 'Noticeably. And if you want, I will go line by line so you can see exactly what you are paying for.' },
    ],
    spot: 1,
    spotNote: 'Validates the anger and the loyalty before offering a single fact.',
    quiz: {
      client: { role: 'Long-time customer, furious', focus: 'Feeling cheated', pain: 'No claims in years, yet his renewal premium went up — threatening to switch' },
      question: 'What is your first move with an angry renewal?',
      hint: 'He wants to be heard before he wants a fact.',
      options: [
        { id: 'A', title: 'Defend the company', text: '"The premium is calculated fairly by our system, sir."' },
        { id: 'B', title: 'Jump to facts', text: '"It went up because of third-party rate revisions."' },
        { id: 'C', title: 'Validate + honour loyalty', text: '"You are right to be angry — and after this many years, you deserve a straight answer, not a script."' },
        { id: 'D', title: 'Offer to switch him', text: '"If you find cheaper elsewhere, you are free to move."' },
      ],
      correct: 'C',
      why: 'An angry customer needs to be heard first; validating the feeling and the loyalty is what makes him listen to the facts.',
      whyBullets: ['Lets him feel heard', 'Acknowledges the relationship', 'Earns the right to explain'],
    },
    lessons: [
      { key: 'service-1', scenario: 'Motor Renewal — Angry About Premium Hike' },
      { key: 'service-2', scenario: 'Claim Worry + Cross-sell' },
    ],
  },
  {
    key: 'growth-1', title: 'Client Growth I — Trust & Whitespace',
    drills: 'Neuro-selling and whitespace mapping — lower the guard, find the unserved need.',
    do: [
      'Create safety before making any case — read their mood first',
      'Explore adjacent needs with curiosity, not a scope-grab',
      'Name their risk before your proposal',
    ],
    dont: [
      'Lead with logic on a defensive stakeholder',
      'Fish for org charts and budgets — earn them',
      'Mistake comfort for agreement',
    ],
    learn: `**Safety before logic.** Senior stakeholders do not resist ideas — they resist *threat*.

1. **Read the mood first.** A defensive person cannot hear a business case.
2. **Name THEIR risk before your proposal.** "Most leaders worry less about a programme's cost and more about sponsoring one that fails — is that closer?" The guard drops on contact.
3. **Whitespace = curiosity, never a land-grab.** "Who handles X today?" asked to understand, not to sell. The unserved need usually hides behind whatever mildly annoys them every week.`,
    watchScript: [
      { speaker: 'customer', text: 'If this is another investment pitch, I will save you time — we are cutting, not spending.' },
      { speaker: 'agent', text: 'Understood — I am not here for budget. Can I ask what is driving the cuts?' },
      { speaker: 'customer', text: 'Board pressure. Everything is numbers this year.' },
      { speaker: 'agent', text: 'Most CFOs I meet are not actually worried about a programme’s cost. They are worried about being the one who sponsored the programme that did not land. Is that closer to it?' },
      { speaker: 'customer', text: '...That is exactly it. We had an ERP rollout that went badly.' },
      { speaker: 'agent', text: 'Then let us not discuss a programme at all. What is small enough to test in one quarter — and cheap enough to kill if it disappoints?' },
    ],
    spot: 3,
    spotNote: 'Names her hidden risk before any proposal — safety first, logic after.',
    quiz: {
      client: { role: 'Defensive CFO', focus: 'Cost control, compliance', pain: 'Under board pressure to cut; a past programme she sponsored went badly' },
      question: 'She opens with "we are cutting, not spending." What now?',
      hint: 'Create safety before any business case.',
      options: [
        { id: 'A', title: 'Push the ROI', text: '"But our programme pays for itself in twelve months."' },
        { id: 'B', title: 'Name her risk', text: '"Most CFOs worry less about a programme\'s cost and more about sponsoring one that fails. Is that closer?"' },
        { id: 'C', title: 'Discount', text: '"We can offer you a special reduced price this quarter."' },
        { id: 'D', title: 'Flatter', text: '"A leader as sharp as you will see the value immediately."' },
      ],
      correct: 'B',
      why: 'Naming her hidden risk creates psychological safety — a defensive stakeholder cannot hear logic until the guard drops.',
      whyBullets: ['Safety before logic', 'Speaks to her real fear, not your product', 'Turns a wall into a conversation'],
    },
    lessons: [
      { key: 'growth1-1', scenario: 'Neuro Selling — The Overloaded VP' },
      { key: 'growth1-2', scenario: 'Neuro Selling — The Comfortable COO' },
      { key: 'growth1-3', scenario: 'Whitespace — The Single-Service Client' },
      { key: 'growth1-4', scenario: 'Neuro Selling — The Defensive CFO' },
      { key: 'growth1-5', scenario: 'Whitespace — The Guarded Process Owner' },
      { key: 'growth1-6', scenario: 'Whitespace — The Fragmented Enterprise' },
    ],
  },
  {
    key: 'growth-2', title: 'Client Growth II — Conversations & The Cookie',
    drills: 'Elevate past status updates, and leave real value behind in every interaction.',
    do: [
      'Bring one specific, credible insight to every meeting',
      'Reframe metrics reviews around THEIR business outcomes',
      'Admit the limits of your data — rigor earns champions',
    ],
    dont: [
      'Walk in with only a status deck',
      'Pitch when asked for insight',
      'Claim "industry best practice" without a source',
    ],
    learn: `**Leave a cookie.** The difference between a vendor and a partner is what remains after you leave the room.

1. **Every interaction leaves ONE thing of value** — an insight, a benchmark, an idea, a warning.
2. **Specific beats broad.** "Claims TAT in your region rose 18%" beats "industry trends are evolving."
3. **Sourced beats confident.** Say where the number comes from — and admit its limits. Rigor earns champions.
4. **Never pitch when asked for insight.** The cookie is free. That is exactly why it works.

Do this every time, and the client starts taking your calls first.`,
    watchScript: [
      { speaker: 'customer', text: 'Right — what have you got for me today? And please, not a capability deck.' },
      { speaker: 'agent', text: 'One number: mid-size retailers in your region cut invoice-processing cost twenty-two percent last year. Median, forty-firm sample, from our own operations data. You are likely paying above that today.' },
      { speaker: 'customer', text: 'Where does that data come from?' },
      { speaker: 'agent', text: 'Our client base — so it skews toward firms that already optimised. Honest caveat. I will send the sector cut so you can judge it yourself.' },
      { speaker: 'customer', text: 'Send it. This is why I take your calls.' },
      { speaker: 'agent', text: 'That is the idea. Next month I am bringing the fraud-flag benchmark — worse news, more useful.' },
    ],
    spot: 1,
    spotNote: 'A specific, sourced, free insight — with no pitch attached. That is the cookie.',
    quiz: {
      client: { role: 'Healthcare CFO', focus: 'Cost control, compliance, efficiency', pain: 'Rising operational cost, pressure to do more with less' },
      question: 'Which story from the Cookie Jar would you use?',
      hint: 'Pick the story that lands on THIS client\'s top priority.',
      options: [
        { id: 'A', title: 'Claims Automation', text: 'Automated 65% of claims, reduced TAT by 40% and improved accuracy.' },
        { id: 'B', title: 'Cost to Value', text: 'Delivered 18% cost savings and reinvested capacity in member care.' },
        { id: 'C', title: 'Member Experience', text: 'Improved NPS by 22 points through personalized member journeys.' },
        { id: 'D', title: 'Compliance & Risk', text: 'Zero audit findings for 3 consecutive years with our quality framework.' },
      ],
      correct: 'B',
      why: 'Cost savings directly connects to the CFO\'s top priority — this story builds instant relevance and credibility.',
      whyBullets: ['Shows measurable financial impact', 'Addresses their core pain', 'Builds confidence in our ability to deliver'],
    },
    lessons: [
      { key: 'growth2-1', scenario: 'Meaningful Conversations — The Status-Update Trap' },
      { key: 'growth2-2', scenario: 'The Cookie — "So, What Have You Got For Me?"' },
      { key: 'growth2-3', scenario: 'Meaningful Conversations — The Transactional Procurement Head' },
      { key: 'growth2-4', scenario: 'The Cookie — The Benchmark Skeptic' },
      { key: 'growth2-5', scenario: 'Meaningful Conversations — The Inherited Stakeholder' },
      { key: 'growth2-6', scenario: 'The Cookie — The Innovation-Fatigued CIO' },
    ],
  },
];

/** Flat list of every lesson with its unit (handy for lookups). */
export const ALL_LESSONS = JOURNEY.flatMap((u) => u.lessons.map((l) => ({ ...l, unit: u.key })));
