"""Which live model serves which language — the whole catalogue, in one table.

GENERATED by scripts/build_live_routing.py from a real probe of every BCP-47 the
app can emit (81 codes) against Gemini 2.5 native audio. Verified 2026-08-11.

Native audio is the only model with `enable_affective_dialog` — it hears the tone in
the learner's voice and answers in kind. It also hard-closes the socket with 1007 on
any language it does not support, so membership here is measured, never assumed.
Re-run the builder after any model change; do not hand-edit the rows.
"""
from __future__ import annotations

from typing import NamedTuple


class LiveRoute(NamedTuple):
    code: str          # BCP-47 sent to Gemini as language_code
    language: str      # human name, for logs and admin
    accent: str | None # accent label when this code is a regional variant
    native: bool       # True -> native audio + affective dialog; False -> flash-live


LIVE_ROUTES: tuple[LiveRoute, ...] = (
    LiveRoute('af-ZA', 'Afrikaans', None, False),
    LiveRoute('sq-AL', 'Albanian', None, False),
    LiveRoute('am-ET', 'Amharic', None, False),
    LiveRoute('ar-XA', 'Arabic', 'Standard Arabic', False),
    LiveRoute('hy-AM', 'Armenian', None, False),
    LiveRoute('az-AZ', 'Azerbaijani', None, False),
    LiveRoute('eu-ES', 'Basque', None, False),
    LiveRoute('bn-IN', 'Bengali', 'Indian', False),
    LiveRoute('bg-BG', 'Bulgarian', None, False),
    LiveRoute('my-MM', 'Burmese', None, False),
    LiveRoute('ca-ES', 'Catalan', None, False),
    LiveRoute('yue-HK', 'Chinese (Cantonese)', None, False),
    LiveRoute('cmn-CN', 'Chinese (Mandarin)', None, False),
    LiveRoute('hr-HR', 'Croatian', None, False),
    LiveRoute('cs-CZ', 'Czech', None, False),
    LiveRoute('da-DK', 'Danish', None, False),
    LiveRoute('nl-NL', 'Dutch', None, True),
    LiveRoute('en-AU', 'English', 'Australian', False),
    LiveRoute('en-GB', 'English', 'British', False),
    LiveRoute('en-IE', 'English', 'Irish', False),
    LiveRoute('en-IN', 'English', 'Indian', False),
    LiveRoute('en-US', 'English', 'American', True),
    LiveRoute('et-EE', 'Estonian', None, False),
    LiveRoute('fil-PH', 'Filipino', None, False),
    LiveRoute('fi-FI', 'Finnish', None, False),
    LiveRoute('fr-CA', 'French', 'Canadian', False),
    LiveRoute('fr-FR', 'French', 'France', True),
    LiveRoute('gl-ES', 'Galician', None, False),
    LiveRoute('ka-GE', 'Georgian', None, False),
    LiveRoute('de-DE', 'German', 'German', True),
    LiveRoute('el-GR', 'Greek', None, False),
    LiveRoute('gu-IN', 'Gujarati', 'Indian', False),
    LiveRoute('ha-NG', 'Hausa', None, False),
    LiveRoute('he-IL', 'Hebrew', None, False),
    LiveRoute('hi-IN', 'Hindi', 'Indian', True),
    LiveRoute('hu-HU', 'Hungarian', None, False),
    LiveRoute('is-IS', 'Icelandic', None, False),
    LiveRoute('ig-NG', 'Igbo', None, False),
    LiveRoute('id-ID', 'Indonesian', None, True),
    LiveRoute('ga-IE', 'Irish', None, False),
    LiveRoute('it-IT', 'Italian', None, True),
    LiveRoute('ja-JP', 'Japanese', None, True),
    LiveRoute('kn-IN', 'Kannada', 'Indian', False),
    LiveRoute('kk-KZ', 'Kazakh', None, False),
    LiveRoute('km-KH', 'Khmer', None, False),
    LiveRoute('ko-KR', 'Korean', None, True),
    LiveRoute('lo-LA', 'Lao', None, False),
    LiveRoute('lv-LV', 'Latvian', None, False),
    LiveRoute('lt-LT', 'Lithuanian', None, False),
    LiveRoute('ms-MY', 'Malay', None, False),
    LiveRoute('ml-IN', 'Malayalam', 'Indian', False),
    LiveRoute('mr-IN', 'Marathi', 'Indian', False),
    LiveRoute('mn-MN', 'Mongolian', None, False),
    LiveRoute('ne-NP', 'Nepali', None, False),
    LiveRoute('nb-NO', 'Norwegian', None, False),
    LiveRoute('fa-IR', 'Persian', None, False),
    LiveRoute('pl-PL', 'Polish', None, True),
    LiveRoute('pt-BR', 'Portuguese', 'Brazilian', True),
    LiveRoute('pt-PT', 'Portuguese', 'European (Portugal)', False),
    LiveRoute('pa-IN', 'Punjabi', 'Indian', False),
    LiveRoute('ro-RO', 'Romanian', None, True),
    LiveRoute('ru-RU', 'Russian', None, True),
    LiveRoute('sr-RS', 'Serbian', None, False),
    LiveRoute('si-LK', 'Sinhala', None, False),
    LiveRoute('sk-SK', 'Slovak', None, False),
    LiveRoute('sl-SI', 'Slovenian', None, False),
    LiveRoute('es-ES', 'Spanish', 'European (Spain)', False),
    LiveRoute('es-US', 'Spanish', 'Latin American', True),
    LiveRoute('sw-KE', 'Swahili', None, False),
    LiveRoute('sv-SE', 'Swedish', None, False),
    LiveRoute('ta-IN', 'Tamil', 'Indian', False),
    LiveRoute('te-IN', 'Telugu', 'Indian', False),
    LiveRoute('th-TH', 'Thai', None, True),
    LiveRoute('tr-TR', 'Turkish', None, True),
    LiveRoute('uk-UA', 'Ukrainian', None, True),
    LiveRoute('ur-IN', 'Urdu', 'Indian', False),
    LiveRoute('uz-UZ', 'Uzbek', None, False),
    LiveRoute('vi-VN', 'Vietnamese', None, True),
    LiveRoute('cy-GB', 'Welsh', None, False),
    LiveRoute('yo-NG', 'Yoruba', None, False),
    LiveRoute('zu-ZA', 'Zulu', None, False),
)

# Indexed once at import. The tuple above is the auditable source of truth; a dict
# lookup just avoids re-scanning 81 rows on every call setup.
_BY_CODE: dict[str, LiveRoute] = {r.code: r for r in LIVE_ROUTES}

NATIVE_CODES: frozenset[str] = frozenset(r.code for r in LIVE_ROUTES if r.native)


def route_for(code: str | None) -> LiveRoute | None:
    """The row for a BCP-47 code, or None when the code is not in the catalogue.

    None must fall back to flash-live: an unknown code on native audio is a 1007
    that kills the call, whereas flash-live accepts every code the app can emit.
    """
    return _BY_CODE.get(code) if code else None
